version: '3.9'

services:
  redis:
    image: 'redis/redis-stack:7.2.0-v1'
    container_name: 'microservices-test-redis'
    ports:
      - 6379:6379
      - 8001:8001

  rabbitmq:
    image: 'rabbitmq:3.12.4-alpine'
    container_name: 'microservices-test-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
